default: community_center_serial

community_center_serial: community_center_serial.c
	gcc -g -O2 --std=c99 -Wall -o community_center_serial community_center_serial.c

clean:
	rm -f community_center_serial
